### ISSUE TITLE
Next VM/370 Sixpack Release

### ISSUE THREAD

**Issue by s390guy** [s390guy/vm370#1]
Add your thoughts about this below.  Note attachments work

**Comment by JimDooey** [comment]
Well, here goes. I’ve been trying to keep up with the numerous commentary regarding GitHub. So for us guys that won’t be contributing (because I don’t have the necessary skills), will we be coming here to get Sixpack updates?  I seem to remember that there might be a v.r.m. methodology for issuing changes.  I also seem to remember that 1.3 Beta is really 1.3.0. Should I treat it as such?  I’m assuming future mods will be 1.3.1, 1.3.2, etc.until the next release. As one could tell, I remain confused.

**Comment by adesutherland** [comment]
Well Jim. Firstly I know little about VM/370 except as a user of old. My interest is getting a decent quality REXX (and therefore C library) working on it. So my experience and approach may very well be completely wrong! 

I wanted to automate my build process ... in sum, scripts fire source code to VM/370, it runs some scripts that build rexx, runs some tests, and creates a tape of the binaries. The host runs in a Docker container.

Anyway the point is that I needed to build a VM/370 host to be this build agent. I started with Beta 3 and via scripts, add updated versions of GCCLIB, BREXX, some weird build tools and relevent CMS and CP mods. I aim (but don't achieve) a new release every fortnight.

But this does not address how people are meant to intercept these releases into their own hosts.

What I have done is added a 7th disk for my local userid and dasd. So I just replace the first 6 disks with those of the new release, run a script to update the DIRECT and timezone, and Boom! Works for me but  not for all. 

For people on the other extreme ... well they can apply Mods etc. as they are experts!

So perhaps for the folks in the middle there should be clear rules as to which disks are owned by the distribution and which are for the user. I know Bob B has some thoughts and plans.

I also think that the distribution should be a ground up rebuild fully scripted ... easy for me to say!

For my stuff ... my next step is to convert all my script, host & docker to REXX. 

Anyway ... just my experience for input to the debate.
