### ISSUE TITLE
New VMCE disks initialized differently

### ISSUE THREAD

**Issue by BobBolch** [s390guy/vm370#15]
Jay Maynard ran into a Hercules issue specific to his environment.
I initialized the new disk volumes using -bz2 instead of -z in dasdinit.
He did not have the bz2 support generated into his Hercules.
For consistancy, all the disk volumes should have been initialized with the
same parameters.

**Comment by s390guy** [comment]
While there is clearly space savings using compression, I would again encourage use of compression outside of Hercules for a distribution.  Whether that is on a volume basis or for the whole distribution is a choice that the distribution providers can decide.  If the use of compression and shadow files is important enough to have a release, then I would encourage a separate distribution that uses compression outside of Hercules.

Personally I think there is value in using separate uncompressed volumes that are compressed using an external tool.  This would provide the opportunity to update individual volumes in the repository without updating all of them or making the release dependent upon how Hercules is built.  This would also facilitate individuals working together to create the release rather than just one.  A web site where the release exists is a good thing.

Part of why so many issues are being discovered now is that this is the first time that the whole release is visible to everyone.

Just my thoughts.

**Comment by BobBolch** [comment]
Correct me if I am wrong, but if I had initialized the volumes with -z, this issue would not have come up. I intend to use -z in the next deliverable.

Compression and shadow files have been used in the VM/370 distributions for over a decade, and my impression now is that many people used that capability for being able to reset their systems. It sounds like copying the compressed volumes to uncompressed volumes is fairly easy. How big a download is too big?

**Comment by g4ugm** [comment]
I did some tests. If you look at the current  release ZIP file, you can see that the DASD  and Shadow files do not compress well. This is to be expected, generally double compression does not achieve much On the other hand, if you create un-compressed drives, and the ZIP them, you get a good compression ratio. So the overall size of the download is similar.

Its only when you expand the distribution that you see a difference. The compressed disks are much smaller than the uncompressed ones.

Uncompressing is simple. The DASDCOPY command with the "-0" option will create an un-compressed DASD and if the "SF=" option is specified merge any shadow files.

**Comment by g4ugm** [comment]
> While there is clearly space savings using compression, I would again encourage use of compression outside of Hercules for a distribution. Whether that is on a volume basis or for the whole distribution is a choice that the distribution providers can decide. If the use of compression and shadow files is important enough to have a release, then I would encourage a separate distribution that uses compression outside of Hercules.
> 
> Personally I think there is value in using separate uncompressed volumes that are compressed using an external tool. This would provide the opportunity to update individual volumes in the repository without updating all of them or making the release dependent upon how Hercules is built. This would also facilitate individuals working together to create the release rather than just one. A web site where the release exists is a good thing.
> 
> Part of why so many issues are being discovered now is that this is the first time that the whole release is visible to everyone.
> 
> Just my thoughts.

All the released pre-built versions of Hercules have all compression types enabled.
I believe Shadow Files provide good utility and you can't do shadow files with uncompressed DASD.
So users would have to compress and enable shadow files. I think this is a bit much for the novice users this is aimed at.
I think so long as we document and ensure consistency we are ok.

**Comment by BobBolch** [comment]
The Hercules disks will be reformated with the same "-z" initialization parameter.

**Comment by BobBolch** [comment]
Fixed in V1 R1.1
