### ISSUE TITLE
CMS edit artifact issue

### ISSUE THREAD

**Issue by GaryDinoNut** [s390guy/vm370#35]
The best way to describe this one is to perform the following steps:  (I did this in maint)
1. type FLIST
2. press PF10  (in my case twice to select USER DIRECT)
3. press PF11 (to edit the file)
4. once in edit type DOWN 20
5. type QUIT

You should now see the bottom line from the bottom of the edit screen on the FLIST panel.  In my case it was 
"USER $TEMP$ NOLOG"

Screen shot attached

![Screenshot from 2021-05-13 22-23-01](https://user-images.githubusercontent.com/84163987/118211352-06326180-b43a-11eb-8997-2de111e24d74.png)

**Comment by BobBolch** [comment]
Added update to blank the line after the PF key line in the FLISTREP ASSEMBLE program and rebuild the FLISTREP MODULE.
This will be fixed in the VM/370 Community Edition V1 R1.2

FLISTREP CLRLAST update file:
./ I 06340000 $ 6340100 100                                           
         MVC   CONSOUT,SPACES                                          CLRLAST
         A        R8,=F'1'       INC THE BUFFER LINE NO           CLRLAST
         ST      R8,BUFLINNO    STORE IT                                CLRLAST
         BAL    R5,WRTBUFLN     WRITE TO THE BUFFER       CLRLAST
./ R 06582200 $ 6582210 10                                            
         S        R1,=F'2'                 rows - 2                             CLRLAST

**Comment by Rhialto** [comment]
Perhaps this also solves the weirdness that happens when you enter EE to edit a file, and then QUIT it. It leave some remaining text at the bottom of the screen, and the terminal is locked for a while and pressing RESET and/or CLEAR, or PA1 etc, does not help.
If this update doesn't fix that, at least I told you about it :)

**Comment by BobBolch** [comment]
I opened a new issue about te FLIST loced screen symptom.

**Comment by BobBolch** [comment]
Fix is staged for V1 R1.2

**Comment by BobBolch** [comment]
Since FLIST and EE are both commands which run in the User area, EE cannot be called from FLIST. Use XXLIST as an alternative.
