### ISSUE TITLE
Alternate Nucleus Space

### ISSUE THREAD

**Issue by Rhialto** [s390guy/vm370#51]
Seeing how HRC075DK adds "alternate nucleus support", it would be great if some free space is available on some disk to make use of this feature. Maybe even two such spaces, if possible.
As I understand it, there can be only one nucleus per DASD so that limits the options.

As for documentation, I think the following is sufficient.

In the MAINT MEMO, which already discusses how to build a nucleus, a paragraph can be added. It should probably tell you to change DMKSYS ASSEMBLE in the proper way (since I assume one would first create a nucleus for the alternate space, test if for a while, and then regenerate it for the normal nucleus space). In particular which space(s) are available, or where to find this information.

As far as I understand it, such a change plus the normal nucleus building plus installing steps would do the trick. I'm currently trying to check in DMKSAV if that also sets up the target disk so you can IPL from it. My remaining knowledge of 370 assembler is really really rusty though :) If it doesn't do this, one would need instructions how to do this oneself.

Thanks for making VM/370 so nice for us poor users who think they know something :)

**Comment by BobBolch** [comment]
This is an advanced non-IBM procedure that very few people, if any, will ever use. The HRC075DK MEMO file on the MAINT 094 disk describes how to setup a new volume with the appropriate disk space for anyone who thinks they should use this.  A much simpler procedure is to copy your existing VMCE system to another directory and test CP experimentl changes on that system. 

Comments?

**Comment by g4ugm** [comment]
II agree Bob. VM/CE is I think it is intended as a ready to run system for the "average" user. I don't see that these need alternate nucleus support. When I ran a real 4381 we never user alternate nucleus support. It was so much simpler to DDR the nucleus to tape, and pop it back it we needed to....

**Comment by marXtevens** [comment]
I agree with Bob & Dave. Long ago & far away, when I was building and testing my next VM/SP or VM/ESA upgrade, I would have a second set of disks that I would mount in a VM to IPL and test. Today, it is easier to have a clone, running in another instance of Hercules, especially as we lack the SP or ESA tools that made that easier to do.

**Comment by Rhialto** [comment]
Ok, I can see the reasoning. I just thought that since the support is built-in, it might make sense to make it easier to use it.

What I tried, by way of spare copy of a nucleus, was to READCARD it into a disk file, after it was punched, That ought to work too, right? At least as long as the system keeps working.

**Comment by BobBolch** [comment]
I don't know why you are using READCARD with a CP Nucleus image.
Please ask questions on the h390 VM list. This area is for reporting system
bugs
or specific documentation errors or omissions only.

I will be glad to answer any questions on the mailing list.

**Comment by BobBolch** [comment]
The requested change will not be made to VMCE. The recommended process for testing CP changes is to use a separate VM instance. This test system can be run in a separate Hercules instance, or could be run in a virtual machine inside your production system.

**Comment by wably** [comment]
As the author of the HRC075DK alternate nucleus support, I'd like to weigh in on this a little bit.  This feature was standard in VM/SP and was essential in our shop back in the day.  I figured out a way to do the same in VM/370.

While it is true that you can simply clone your dasd and test changes on a copy, or use DDR to backup a nucleus and restore it the same way, both are a bit of a bother.  With an alternate nucleus I can simply IPL the alternate volume and I am back up in an instant and everything else remains the same in the directory or in the spool.

I change to the alternate every time I build a CP nucleus.  I just rock back and forth between the two volumes, so I can always go back to the previous good build.  On another copy of the system, I use the alternate so that the nucleus on one volume has a V=R area and the other does not.

No extra volumes are needed; any existing volume can become an alternate by ensuring that the nucleus area cylinders are available and unallocated by minidisks on the alternate volume, at the same exact cylinder numbers.  The ERR, CKP, and WRM areas do not have to be replicated.

Regards,
Bob

**Comment by BobBolch** [comment]
Hi Bob,

Is there any end user documentation on how to use this facility?
Considering that only a small
number of hobbyists ever install a modification, or even generate a new
SYSID, I don't
want to have a question generator. :-)

It's pretty easy to copy a Hercules DASD directory, make a CP change, and
copy the backup
directory back to the DASD directory if things go south.

It sounds like we would supply a reserved area on a SYSOWNed volume, but
would we need
an alternate DMKSYS and load list? Would you be able to do a writeup (or
swipe some section
from a VM/SP book)?

Thanks/Bob

**Comment by BobBolch** [comment]
Actually, the HRC075DK MEMO describes this very well.
Bob

**Comment by wably** [comment]
Hi Bob,

No alternate load list is needed.  

Ideally, the nucleus cylinders should be in the same place on each IPLable volume, but it doesn't strictly have to be the case.  Its just that by putting them in the same place it is one less thing to fat finger when you want to build a nucleus on an alternate, to have to remember to change the cylinder numbers in SYSNUC each time.  I'd keep them the same.

Then, all you have to do to really use the facility each time you build a nucleus or whenever you want a backup nucleus:

1. make whatever changes you intended for why you are building a nucleus in the first place.
2. edit DMKSYS to change the SYSVOL= and SYSRES= to reflect the new volser and CUU; then assemble DMKSYS
3. Build your nucleus as usual
4. IPL from the volume you placed the new nucleus on.

Also, please note that HRC075DK is already installed on VMCE and the volser is already specified for SYSERR,SYSCKP,SYSWRM in DMKSYS; it is just a matter of making space for another nucleus on another volume.

Regards,
Bob

**Comment by BobBolch** [comment]
I would find it less confusing to have a DMKSYS2 ASSEMBLE file with the alternate SYSVOL and SYSRES, and an alternate load list with DMKSYS2 in it, rather than DMKSYS. 

Is it sufficient to resolve this issue by providing (and documenting) the alternate nucleus cylinders on an alternate volume?

**Comment by wably** [comment]
In my opinion, having a DMKSYS2 would be worse, because then you have to maintain two of them.  Make a change in one (say, to change time zones for daylight saving time) and now you have to make sure those changes are migrated to the other.

> Is it sufficient to resolve this issue by providing (and documenting) the alternate nucleus cylinders on an alternate volume?

Yes.

What you wrote earlier in this issue that most users would not use this is certainly true. I wouldnt complicate things by having duplicate load lists and so on. Just a second area reserved for the nucleus would be sufficient. If someone then wants to use it, it is all set for them; just read the instructions to learn to specify the alternate SYSVOL/SYSRES and build.  That's what VM/CE is all about: having a lot of stuff installed and ready to go.  No one will use all of it though.

Also, please note that the mention in the HRC075DK MEMO documentation of the shutdown error will not happen on VM/CE.  This is because HRC075DK is already installed and so the checkpoint/warm start code is already in sync.

Regards,
Bob

**Comment by BobBolch** [comment]
To each there own view of what's easier :-)

Bob, I will add preallocated and formatted space on VM50-3 at cylinder 530 for 19 cylinders, to match the location of the primary nucleus space on VM50-1. I will also update the HRC075DK MEMO file as you pointed out, and document the alternate cylinder location. If you review the MEMO change (I'll email it), we can wrap this up.
/Bob
